from yattag import Doc
import codecs
import re

print("#####################################")
print("     Whatsapp Messages to HTML")
print("-------------------------------------")


from datetime import datetime
def getTime():
	now = datetime.now()
	year = now.strftime("%Y")
	month = now.strftime("%m")
	day = now.strftime("%d")
	time = now.strftime("%H_%M_%S")
	date_time = now.strftime("%m_%d_%Y_%H_%M_%S")
	return str(date_time)
    
def deEmojify(inputString):
    return inputString.encode('ascii', 'ignore').decode('ascii')

def find_between_r( s, first, last ):
    try:
        start = s.rindex( first ) + len( first )
        end = s.rindex( last, start )
        return s[start:end]
    except ValueError:
        return " "

print("Please select how page is generated by typing number.")
print("1. Full page")

while True :
    mode = input(" ")
    if mode == "1" or mode == "2":
        break



while(True):
    filename = input("Give filename (file must be in same folder as this program and must be .txt):")
    filename = filename+".txt"
    lines = []
    try:
        with open(filename, encoding="utf8") as fp:
            line = fp.readline()
            line = deEmojify(line)
            cnt = 1
            while line:
                if 1 == 1:
                    print("Processing line: "+str(cnt))
                    '''
                    if line.strip().split("-")[0][0].isdigit():
                        ts = line.strip().split("-")[0]
                        ts = str(ts)
                    else:
                        ts = " "
                    '''

                    x = re.search("(?<=)(.*)(?=-) *-(.*?):(.*)", str(line.strip()))
                    #print(x.group(1))
                    #print(x.group(2))
                    #print(x.group(3))

                    if x:
                        time = x.group(1)
                        person = x.group(2)
                        text = x.group(3)
                    else:
                        r = re.search("(.+?(?=-)).*\-(.*)", str(line.strip()))
                        if r:
                            time = r.group(1)
                            text = r.group(2)
                            person = "[UNKNOWN]"
                        else:
                            print("Error while processing: "+str(cnt))



                    try:
                        time
                    except NameError:
                        time = " "

                    try:
                        person
                    except NameError:
                        person = " "

                    try:
                        text
                    except NameError:
                        text = " "
                        
                    
                    data = {
                        "line":str(cnt),
                        "time":time,
                        "person":person,
                        "text":text
                    }
                    lines.append(data)
                
                    #print("Error printing line it may have emojis: "+str(cnt))
                    
                line = fp.readline()
                cnt += 1
            break;
    except:
        print("Error (Maby file not found?)")



doc, tag, text = Doc().tagtext()
doc.asis('<!DOCTYPE html>')
with tag('html'):
    doc.asis('<head> <title>Conversation</title> <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> <script src="https://code.jquery.com/jquery-3.4.1.slim.js" integrity="sha256-BTlTdQO9/fascB1drekrDVkaKd9PkwBymMlHOiG+qLI=" crossorigin="anonymous"></script> <script src="script.js"></script> <meta name="viewport" content="width=device-width,initial-scale=1.0"> <meta charset="utf-8"> </head>')

    with tag('body'):
        with tag('div', klass='container'):
            with tag('div', klass='row'):
                with tag('div', klass='col-md-12'):
                    doc.asis('  <table class="table"><thead><tr><th>Line</th><th>Timestamp</th><th>Person</th><th>Message</th></tr></thead><tbody>')
                    for i in lines:
                        doc.asis('<tr><td>'+i['line']+'</td><td>'+i['time']+'</td><td>'+i['person']+'</td><td>'+i['text']+'</td></tr>')
                    doc.asis('</tbody></table>')

result = doc.getvalue()

f = codecs.open("wa_page_"+getTime()+".html", "a", "utf-8")
f.write(result)
f.close()
print("#####################################")
print("          Processing done")
print("-------------------------------------")

